# Generated by Django 5.1.6 on 2025-03-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0007_rename_user_name_client_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='User',
        ),
    ]
